Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2022-11, with the labels that each got.

#187 Adapt functions DefineDiffusion, DefineImplicit and Geometry
  src/define_diffusion.jl
  src/define_implicit.jl
  src/geometry.jl
Labels: gpu

#188 Geopotential calculation
  src/SpeedyWeather.jl
  src/boundaries.jl
  src/diagnostic_variables.jl
  src/geometry.jl
  src/geopotential.jl
  test/geopotential.jl
  test/initialize.jl
  test/runtests.jl
Labels: vertical, dynamics

#189 Surface pressure tendency
  src/deprecated.jl
  src/diagnostic_variables.jl
  src/geometry.jl
  src/spectral_gradients.jl
  src/tendencies_dynamics.jl
  test/spectral_gradients.jl
  test/surface_press_tend.jl
Labels: vertical, dynamics

#195 add_tendencies! updated to LowerTriangularMatrix
  src/tendencies.jl
Labels: enhancement, array types

#196 Bernoulli potential for PrimitiveEquation
  src/default_parameters.jl
  src/tendencies_dynamics.jl
  test/geopotential.jl
Labels: dynamics

#197 Virtual temperature calculation
  src/constants.jl
  src/default_parameters.jl
  src/define_diffusion.jl
  src/diagnostic_variables.jl
  src/geometry.jl
  src/geopotential.jl
  src/initial_conditions.jl
  test/geopotential.jl
Labels: dynamics
