Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2022-09, with the labels that each got.

#142 Inverse Laplace ∇⁻²! via kernel in ∇²!
  src/spectral_gradients.jl
  src/spectral_transform.jl
  test/spectral_gradients.jl
Labels: transform

#144 Interface relaxation with seasonal cycle
  docs/src/how_to_run_speedy.md
  src/boundaries.jl
  src/constants.jl
  src/default_parameters.jl
  src/output.jl
  src/tendencies.jl
  src/tendencies_dynamics.jl
  src/time_integration.jl
Labels: parameterizations, forcing

#143 Adapt structures for diagnostic variables and prognostic variables
  .github/workflows/Documenter.yml
  src/diagnostic_variables.jl
  src/prognostic_variables.jl
Labels: gpu

#154 set_vars! function to easily set variables in PrognosticVariables
  src/initial_conditions.jl
  src/models.jl
  src/prognostic_variables.jl
  test/run_speedy_with_output.jl
  test/runtests.jl
  test/set_vars.jl
Labels: array types
