Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2023-04, with the labels that each got.

#278 Hyper diffusion overhauled
  src/SpeedyWeather.jl
  src/abstract_types.jl
  src/default_parameters.jl
  src/dynamics/constants.jl
  src/dynamics/define_diffusion.jl
  src/dynamics/diffusion.jl
  src/dynamics/tendencies_dynamics.jl
  src/physics/shortwave_radiation.jl
  src/run_speedy.jl
  test/diffusion.jl
Labels: testing, dynamics

#279 primitive equation video in readme
  README.md
Labels: documentation

#280 TemperatureRelaxation, BoundaryLayer type stable
  src/RingGrids/grids_general.jl
  src/abstract_types.jl
  src/default_parameters.jl
  src/dynamics/diagnostic_variables.jl
  src/physics/column_variables.jl
  src/physics/constants.jl
  src/physics/define_column.jl
  src/physics/parameter_structs.jl
  src/physics/temperature_relaxation.jl
  src/physics/tendencies.jl
  test/runtests.jl
Labels: performance, style, parameterizations

#284 Add spaces after commas
  README.md
Labels: documentation

#283 Missing `(-1)^{n+1}` factor from hyperdiffusion term
  docs/src/dynamical_core.md
  src/dynamics/define_diffusion.jl
  src/dynamics/diffusion.jl
Labels: documentation, dynamics

#288 Docs for `Parameters`
  Project.toml
  src/SpeedyTransforms/spectral_gradients.jl
  src/default_parameters.jl
Labels: documentation

#291 Better docs rendering
  src/SpeedyTransforms/spectral_gradients.jl
  src/SpeedyTransforms/spectral_transform.jl
  src/SpeedyTransforms/spectral_truncation.jl
  src/dynamics/parameter_structs.jl
  src/dynamics/tendencies_dynamics.jl
  src/physics/longwave_radiation.jl
  test/geopotential.jl
Labels: documentation

#292 Diffusion tapering for stratosphere
  src/dynamics/define_diffusion.jl
  src/dynamics/diffusion.jl
  src/run_speedy.jl
  test/diffusion.jl
Labels: testing, dynamics

#290 Dealiasing parameter for quad,cub truncation
  src/RingGrids/RingGrids.jl
  src/RingGrids/full_grids.jl
  src/RingGrids/grids_general.jl
  src/RingGrids/healpix.jl
  src/RingGrids/octahealpix.jl
  src/RingGrids/octahedral.jl
  src/RingGrids/utility_functions.jl
  src/SpeedyTransforms/SpeedyTransforms.jl
  src/SpeedyTransforms/aliasing.jl
  src/SpeedyTransforms/spectral_transform.jl
  src/default_parameters.jl
  src/dynamics/geometry.jl
  test/spectral_transform.jl
  test/utility_functions.jl
Labels: performance, transform

#295 Bump up julia requirement to v1.8
  Project.toml
Labels: dependency, package

#293 Fix typo in docs: julia v1.78 -> v1.8
  docs/src/index.md
Labels: documentation

#287 restructure PrognosticVariables
  src/SpeedyWeather.jl
  src/dynamics/diffusion.jl
  src/dynamics/geopotential.jl
  src/dynamics/implicit.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/planets.jl
  src/dynamics/prognostic_variables.jl
  src/dynamics/scaling.jl
  src/dynamics/tendencies.jl
  src/dynamics/tendencies_dynamics.jl
  src/dynamics/time_integration.jl
  src/output/feedback.jl
  src/output/output.jl
  src/output/pretty_printing.jl
  test/diffusion.jl
  test/geopotential.jl
  test/initialize.jl
  test/run_speedy.jl
  test/run_speedy_with_output.jl
  test/set_vars.jl
  test/spectral_gradients.jl
  test/spectral_transform.jl
  test/time_stepping.jl
Labels: structure, dynamics

#301 Progress.txt output with speed and ETA
  src/output/feedback.jl
  src/output/pretty_printing.jl
  src/run_speedy.jl
  src/utility_functions.jl
Labels: user interface

#303 new time step scaling following Jablonowski
  src/default_parameters.jl
  src/dynamics/constants.jl
  test/netcdf_output.jl
Labels: dynamics

#302 Temperature relaxation towards Jablonowski's profile
  src/SpeedyWeather.jl
  src/default_parameters.jl
  src/dynamics/define_implicit.jl
  src/dynamics/diagnostic_variables.jl
  src/dynamics/implicit.jl
  src/dynamics/parameter_structs.jl
  src/dynamics/tendencies.jl
  src/dynamics/tendencies_dynamics.jl
  src/dynamics/time_integration.jl
  src/physics/constants.jl
  src/physics/parameter_structs.jl
  src/physics/temperature_relaxation.jl
Labels: forcing, vertical, dynamics

#305 ETA and speedstring in progress.txt got lost
  src/output/feedback.jl
  src/output/pretty_printing.jl
Labels: user interface

#307 Power spectrum analysis
  src/SpeedyTransforms/SpeedyTransforms.jl
  src/SpeedyTransforms/spectrum.jl
Labels: transform
