Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2023-06, with the labels that each got.

#343 barotropic, shallowwater test cases
  README.md
  docs/img/barotropic_vorticity.jpg
  docs/img/galewsky.jpg
  docs/img/galewsky_nc_12days.png
  docs/img/galewsky_nc_12days_mountains.png
  docs/img/galewsky_nc_6days.png
  docs/src/how_to_run_speedy.md
  src/SpeedyWeather.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/models.jl
Labels: documentation

#332 Add clarification for SWE variables
  docs/src/dynamical_core.md
Labels: documentation

#338 SpeedyCondensation implemented
  src/SpeedyWeather.jl
  src/abstract_types.jl
  src/dynamics/atmospheres.jl
  src/dynamics/constants.jl
  src/dynamics/horizontal_diffusion.jl
  src/dynamics/implicit.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/models.jl
  src/dynamics/orography.jl
  src/dynamics/planets.jl
  src/dynamics/spectral_grid.jl
  src/dynamics/time_integration.jl
  src/dynamics/vertical_coordinates.jl
  src/output/output.jl
  src/physics/boundary_layer.jl
  src/physics/column_variables.jl
  src/physics/convection.jl
  src/physics/define_column.jl
  src/physics/large_scale_condensation.jl
  src/physics/shortwave_radiation.jl
  src/physics/temperature_relaxation.jl
  src/physics/tendencies.jl
  src/physics/thermodynamics.jl
  src/physics/vertical_diffusion.jl
Labels: parameterizations, humidity

#346 Plot `::AbstractGrid` as Unicode heatmap
  docs/make.jl
  docs/src/ringgrids.md
  src/RingGrids/RingGrids.jl
  src/RingGrids/grids_general.jl
  src/RingGrids/interpolation.jl
  src/RingGrids/show.jl
  src/SpeedyWeather.jl
  src/dynamics/prognostic_variables.jl
Labels: user interface, array types, output

#351 Fix typos in docs
  docs/src/dynamical_core.md
  docs/src/grids.md
  docs/src/how_to_run_speedy.md
  docs/src/parametrizations.md
  docs/src/ringgrids.md
  docs/src/spectral_transform.md
Labels: documentation

#353 Move clock to prognostic variables
  src/SpeedyWeather.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/models.jl
  src/dynamics/prognostic_variables.jl
  src/dynamics/time_integration.jl
  src/output/output.jl
  src/run_speedy.jl
  test/netcdf_output.jl
Labels: structure

#354 plot small grids without spaces
  src/RingGrids/show.jl
  src/dynamics/horizontal_diffusion.jl
Labels: user interface

#355 Non-adaptive implicit: temp_profile in implicit only
  src/dynamics/implicit.jl
  src/dynamics/tendencies.jl
  src/dynamics/tendencies_dynamics.jl
  src/dynamics/time_integration.jl
  src/output/feedback.jl
Labels: dynamics

#348 Barotropic, shallow water, and some primitive model documentation
  README.md
  docs/make.jl
  docs/src/barotropic.md
  docs/src/boundary_conditions.md
  docs/src/dynamical_core.md
  docs/src/functions.md
  docs/src/grids.md
  docs/src/how_to_run_speedy.md
  docs/src/index.md
  docs/src/installation.md
  docs/src/lowertriangularmatrices.md
  docs/src/output.md
  docs/src/parameterizations.md
  docs/src/primitiveequation.md
  docs/src/ringgrids.md
  docs/src/shallowwater.md
  docs/src/spectral_transform.md
  docs/src/speedytransforms.md
  docs/src/time_integration.md
  src/dynamics/implicit.jl
  src/dynamics/tendencies.jl
  src/dynamics/tendencies_dynamics.jl
  src/dynamics/time_integration.jl
  test/time_stepping.jl
Labels: documentation

#357 CompatHelper: bump compat for KernelAbstractions to 0.9, (keep existi…
  Project.toml
  src/SpeedyWeather.jl
  src/gpu.jl
  test/kernelabstractions.jl
Labels: gpu, dependency

#360 Other video for primitive
  README.md
Labels: documentation

#361 CI tests on Julia 1.8, 1.9 + test on Julia nightly every week
  .github/workflows/CI.yml
  .github/workflows/julianightly.yml
Labels: testing
