Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2023-05, with the labels that each got.

#308 HyperDiffusion and VerticalDiffusion
  src/SpeedyTransforms/spectral_truncation.jl
  src/SpeedyWeather.jl
  src/abstract_types.jl
  src/default_parameters.jl
  src/dynamics/boundaries.jl
  src/dynamics/constants.jl
  src/dynamics/define_diffusion.jl
  src/dynamics/diffusion.jl
  src/dynamics/implicit.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/parameter_structs.jl
  src/physics/boundary_layer.jl
  src/physics/column_variables.jl
  src/physics/constants.jl
  src/physics/define_column.jl
  src/physics/parameter_structs.jl
  src/physics/temperature_relaxation.jl
  src/physics/tendencies.jl
  src/physics/thermodynamics.jl
  src/physics/vertical_diffusion.jl
  test/netcdf_output.jl
Labels: testing, parameterizations, dynamics

#312 @unpack + import Paramters removed
  Project.toml
  src/RingGrids/RingGrids.jl
  src/RingGrids/interpolation.jl
  src/SpeedyTransforms/SpeedyTransforms.jl
  src/SpeedyTransforms/spectral_gradients.jl
  src/SpeedyTransforms/spectral_transform.jl
  src/SpeedyWeather.jl
  src/dynamics/boundaries.jl
  src/dynamics/constants.jl
  src/dynamics/define_diffusion.jl
  src/dynamics/diagnostic_variables.jl
  src/dynamics/geometry.jl
  src/dynamics/geopotential.jl
  src/dynamics/implicit.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/parameter_structs.jl
  src/dynamics/scaling.jl
  src/dynamics/tendencies.jl
  src/dynamics/tendencies_dynamics.jl
  src/dynamics/time_integration.jl
  src/output/feedback.jl
  src/output/output.jl
  src/physics/convection.jl
  src/physics/large_scale_condensation.jl
  src/physics/longwave_radiation.jl
  src/physics/shortwave_radiation.jl
  src/physics/thermodynamics.jl
Labels: style, structure

#313 Parameterization fluxes and dry static energy diffusion
  src/default_parameters.jl
  src/physics/column_variables.jl
  src/physics/define_column.jl
  src/physics/tendencies.jl
  src/physics/vertical_diffusion.jl
Labels: parameterizations

#316 Keepbits per variable
  src/default_parameters.jl
  src/output/output.jl
  src/physics/tendencies.jl
Labels: data, output, new defaults

#221 Add mini development notes
  docs/make.jl
  docs/src/development.md
Labels: documentation

#318 Avoid type instability in fluxes_to_tendencies!
  src/physics/tendencies.jl
Labels: performance

#321 Some docs improvements
  .github/workflows/DocPreviewCleanup.yml
  docs/make.jl
  docs/src/how_to_run_speedy.md
  src/run_speedy.jl
Labels: documentation

#179 Update copyright and licensing information
  LICENSE.txt
  README.md
  ThirdPartyNotices.txt
Labels: license

#326 Add compat entry for FLoops
  Project.toml
Labels: compatibility, package

#324 Update TagBot.yml
  .github/workflows/TagBot.yml
Labels: package

#330 1st order upwind scheme for vertical advection
  src/dynamics/tendencies_dynamics.jl
Labels: vertical, dynamics

#314 docs minor stuff
  docs/src/grids.md
  docs/src/index.md
Labels: documentation

#335 RingGrids and LowerTriangularMatrices docs
  .gitignore
  docs/make.jl
  docs/src/extending.md
  docs/src/grids.md
  docs/src/index.md
  docs/src/installation.md
  docs/src/lowertriangularmatrices.md
  docs/src/ringgrids.md
  docs/src/speedytransforms.md
  src/LowerTriangularMatrices/LowerTriangularMatrices.jl
  src/RingGrids/RingGrids.jl
  src/RingGrids/grids_general.jl
  src/RingGrids/interpolation.jl
  src/SpeedyTransforms/SpeedyTransforms.jl
Labels: documentation

#336 remove Model from SpectralGrid
  README.md
  src/dynamics/diagnostic_variables.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/models.jl
  src/dynamics/spectral_grid.jl
  src/output/output.jl
  src/run_speedy.jl
  test/column_variables.jl
  test/diffusion.jl
  test/geopotential.jl
  test/netcdf_output.jl
  test/run_speedy.jl
  test/set_vars.jl
  test/spectral_gradients.jl
  test/vertical_levels.jl
Labels: structure

#337 Update README.md
  README.md
Labels: documentation

#339 Update README.md
  README.md
  docs/make.jl
  docs/src/output.md
Labels: documentation

#340 NetCDF output documented
  docs/src/output.md
  src/output/output.jl
Labels: documentation

#341 Barotropic vorticity equation algorithm described
  docs/src/dynamical_core.md
Labels: documentation
