Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2023-12, with the labels that each got.

#421 JOSS badge added
  README.md
Labels: documentation

#420 Period Keyword Argument instead of n_days
  README.md
  docs/src/how_to_run_speedy.md
  docs/src/output.md
  docs/src/setups.md
  docs/src/speedytransforms.md
  src/SpeedyWeather.jl
  src/dynamics/prognostic_variables.jl
  src/output/feedback.jl
  src/run_speedy.jl
  test/dates.jl
  test/netcdf_output.jl
  test/run_speedy.jl
  test/vertical_advection.jl
Labels: user interface, time integration

#424 Stochastic stirring video
  README.md
Labels: documentation

#423 Make prognostics available for forcing, drag in Barotropic/SWM
  docs/src/extending.md
  src/SpeedyTransforms/spectral_truncation.jl
  src/dynamics/drag.jl
  src/dynamics/forcing.jl
  src/dynamics/tendencies.jl
  src/dynamics/tendencies_dynamics.jl
  src/dynamics/time_integration.jl
  test/extending.jl
  test/geopotential.jl
  test/runtests.jl
Labels: structure, forcing, dynamics
