Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2023-08, with the labels that each got.

#356 SpectralTransform for square LowerTriMats too
  src/SpeedyTransforms/spectral_transform.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/prognostic_variables.jl
  src/dynamics/spectral_grid.jl
  test/diffusion.jl
  test/set_vars.jl
  test/spectral_gradients.jl
Labels: user interface, transform

#363 SpeedyTransforms documentation
  Project.toml
  docs/Project.toml
  docs/src/grids.md
  docs/src/speedytransforms.md
  docs/src/time_integration.md
  src/RingGrids/RingGrids.jl
  src/RingGrids/similar.jl
  src/SpeedyTransforms/SpeedyTransforms.jl
  src/SpeedyTransforms/show.jl
  src/SpeedyTransforms/spectral_transform.jl
  src/dynamics/constants.jl
  src/dynamics/spectral_grid.jl
Labels: documentation, user interface, transform

#364 Increase test tolerance
  test/spectral_gradients.jl
Labels: testing

#362 Different vertical advection schemes
  .gitignore
  src/SpeedyWeather.jl
  src/abstract_types.jl
  src/dynamics/diagnostic_variables.jl
  src/dynamics/models.jl
  src/dynamics/tendencies_dynamics.jl
  src/dynamics/vertical_advection.jl
  test/runtests.jl
  test/vertical_advection.jl
Labels: vertical, dynamics

#365 Primitive equation documentation
  docs/make.jl
  docs/src/index.md
  docs/src/output.md
  docs/src/primitiveequation.md
  docs/src/shallowwater.md
  src/dynamics/constants.jl
  src/dynamics/tendencies.jl
  src/dynamics/tendencies_dynamics.jl
  src/dynamics/vertical_coordinates.jl
Labels: documentation

#369 Speedstring precompilation warning
  src/dynamics/models.jl
  src/output/feedback.jl
Labels: bug, dependency

#371 Full and octahedral Gaussian grid documented
  docs/src/grids.md
Labels: documentation
