Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2024-04, with the labels that each got.

#506 Broadcasting for RingGrids
  docs/src/analysis.md
  docs/src/speedytransforms.md
  src/RingGrids/RingGrids.jl
  src/RingGrids/full_grids.jl
  src/RingGrids/grids_general.jl
  src/RingGrids/healpix.jl
  src/RingGrids/octahealpix.jl
  src/RingGrids/octahedral.jl
  src/dynamics/tendencies.jl
  test/grids.jl
Labels: user interface :musical_keyboard:, array types :globe_with_meridians:

#510 Large-scale condensation documented
  .gitignore
  docs/src/analysis.md
  docs/src/callbacks.md
  docs/src/forcing_drag.md
  docs/src/how_to_run_speedy.md
  docs/src/large_scale_condensation.md
  docs/src/lowertriangularmatrices.md
  docs/src/particles.md
  docs/src/ringgrids.md
  docs/src/setups.md
Labels: documentation :books:, humidity :droplet:

#512 Convection documentation
  docs/src/barotropic.md
  docs/src/convection.md
  docs/src/index.md
  docs/src/large_scale_condensation.md
  src/physics/longwave_radiation.jl
Labels: documentation :books:, parameterizations :cloud_with_rain:, humidity :droplet:

#511 Add Makie extension
  Project.toml
  README.md
  docs/Project.toml
  docs/make.jl
  docs/src/analysis.md
  docs/src/examples.md
  docs/src/forcing_drag.md
  docs/src/how_to_run_speedy.md
  docs/src/installation.md
  docs/src/particles.md
  ext/SpeedyWeatherMakieExt.jl
  src/RingGrids/show.jl
  src/dynamics/drag.jl
Labels: user interface :musical_keyboard:, dependency :guide_dog:

#513 Radiation documentation
  docs/src/radiation.md
Labels: documentation :books:

#514 Held-Suarez example, NoTypes for surface fluxes
  README.md
  docs/make.jl
  docs/src/convection.md
  docs/src/examples_2D.md
  docs/src/examples_3D.md
  docs/src/forcing_drag.md
  docs/src/how_to_run_speedy.md
  docs/src/installation.md
  docs/src/large_scale_condensation.md
  docs/src/output.md
  docs/src/radiation.md
  docs/src/speedytransforms.md
  src/models/primitive_dry.jl
  src/models/primitive_wet.jl
  src/physics/surface_fluxes.jl
  src/physics/temperature_relaxation.jl
Labels: documentation :books:, surface :mountain:

#517 Remove PythonPlot dependency of docs
  docs/Project.toml
Labels: dependency :guide_dog:, package :package:

#519 Model construction without type constraints
  .github/workflows/CI.yml
  Project.toml
  docs/src/how_to_run_speedy.md
  docs/src/installation.md
  docs/src/structure.md
  src/models/barotropic.jl
  src/models/primitive_dry.jl
  src/models/primitive_wet.jl
  src/models/shallow_water.jl
Labels: bug :lady_beetle:, model :control_knobs:, compatibility :dancers:

#523 Exports more gradient operators from SpeedyTransforms
  docs/make.jl
  docs/src/gradients.md
  docs/src/speedytransforms.md
  src/SpeedyTransforms/SpeedyTransforms.jl
  src/SpeedyTransforms/spectral_gradients.jl
  src/SpeedyTransforms/spectral_transform.jl
  src/SpeedyTransforms/spectrum.jl
  src/SpeedyWeather.jl
Labels: user interface :musical_keyboard:, transform :arrow_left: :arrow_right:

#503 LowerTriangularMatrices: N-dimensional and GPU ready
  Project.toml
  docs/src/lowertriangularmatrices.md
  src/LowerTriangularMatrices/LowerTriangularMatrices.jl
  src/LowerTriangularMatrices/lower_triangular_matrix.jl
  src/SpeedyTransforms/spectral_truncation.jl
  src/SpeedyWeather.jl
  test/lower_triangular_matrix.jl
  test/spectral_gradients.jl
Labels: gpu :framed_picture:, array types :globe_with_meridians:

#520 AbstractGridArray N-dimensional and GPU ready
  Project.toml
  docs/src/output.md
  ext/SpeedyWeatherJLArraysExt.jl
  ext/SpeedyWeatherMakieExt.jl
  src/RingGrids/RingGrids.jl
  src/RingGrids/full_grids.jl
  src/RingGrids/general.jl
  src/RingGrids/grids/full_clenshaw.jl
  src/RingGrids/grids/full_gaussian.jl
  src/RingGrids/grids/full_healpix.jl
  src/RingGrids/grids/full_octahealpix.jl
  src/RingGrids/grids/healpix.jl
  src/RingGrids/grids/octahealpix.jl
  src/RingGrids/grids/octahedral_clenshaw.jl
  src/RingGrids/grids/octahedral_gaussian.jl
  src/RingGrids/grids_general.jl
  src/RingGrids/healpix.jl
  src/RingGrids/interpolation.jl
  src/RingGrids/octahedral.jl
  src/RingGrids/quadrature_weights.jl
  src/RingGrids/reduced_grids.jl
  src/RingGrids/scaling.jl
  src/RingGrids/show.jl
  src/RingGrids/similar.jl
  src/RingGrids/utility_functions.jl
  src/SpeedyTransforms/spectral_transform.jl
  src/SpeedyWeather.jl
  src/dynamics/spectral_grid.jl
  src/output/output.jl
  test/grids.jl
  test/lower_triangular_matrix.jl
Labels: gpu :framed_picture:, array types :globe_with_meridians:

#524 Change weight in ZonalJet()
  src/dynamics/initial_conditions.jl
Labels: dynamics :wavy_dash:, initial conditions :traffic_light:

#526 Orography documented
  docs/src/orography.md
  src/SpeedyWeather.jl
  src/dynamics/orography.jl
Labels: documentation :books:, input data :floppy_disk:

#528 Particle advection time stepping corrected
  src/dynamics/particle_advection.jl
  src/dynamics/particles.jl
  src/dynamics/time_integration.jl
  test/spectral_gradients.jl
Labels: time integration :clock10:, particles :balloon:

#529 Humidity video for readme
  README.md
Labels: documentation :books:
