Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2024-03, with the labels that each got.

#468 Add dependabot
  .github/dependabot.yml
  .github/workflows/CI.yml
Labels: testing :test_tube:, dependency :guide_dog:

#470 Remove DEFAULT_NF generators of Earth and EarthAtmosphere
  docs/src/setups.md
  src/dynamics/atmosphere.jl
  src/dynamics/planet.jl
  test/spectral_transform.jl
Labels: low precision :steam_locomotive:, user interface :musical_keyboard:

#467 Dry Betts-Miller convection
  src/models/primitive_dry.jl
  src/models/primitive_wet.jl
  src/physics/column_variables.jl
  src/physics/convection.jl
Labels: parameterizations :cloud_with_rain:

#476 Remove testing for 1.8 and 1.9 temporarily
  .github/workflows/CI.yml
Labels: testing :test_tube:

#475 Fix the Docs/SpeedyTransforms/Geostrophy example + make it run live by doc built
  docs/src/speedytransforms.md
  src/output/callbacks.jl
Labels: documentation :books:

#469 Initial conditions modular for variables
  src/dynamics/atmosphere.jl
  src/dynamics/initial_conditions.jl
  src/models/barotropic.jl
  src/models/primitive_dry.jl
  src/models/primitive_wet.jl
  src/models/shallow_water.jl
Labels: user interface :musical_keyboard:, structure :house:

#479 Delete deprecated doc instructions
  docs/src/forcing_drag.md
Labels: documentation :books:

#465 Particle advection in 2D, all models
  .gitignore
  docs/make.jl
  docs/src/particles.md
  src/RingGrids/interpolation.jl
  src/SpeedyWeather.jl
  src/dynamics/abstract_types.jl
  src/dynamics/atmosphere.jl
  src/dynamics/diagnostic_variables.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/particle_advection.jl
  src/dynamics/particles.jl
  src/dynamics/planet.jl
  src/dynamics/prognostic_variables.jl
  src/dynamics/scaling.jl
  src/dynamics/spectral_grid.jl
  src/dynamics/time_integration.jl
  src/models/barotropic.jl
  src/models/primitive_dry.jl
  src/models/primitive_wet.jl
  src/models/shallow_water.jl
  src/models/simulation.jl
  src/output/feedback.jl
  src/output/particle_tracker.jl
  test/particle_advection.jl
  test/particles.jl
  test/runtests.jl
Labels: performance :rocket:, dynamics :wavy_dash:, time integration :clock10:

#481 Add `@id`s for model pages + add links to models pages in Docs landing page
  docs/src/barotropic.md
  docs/src/forcing_drag.md
  docs/src/how_to_run_speedy.md
  docs/src/index.md
  docs/src/installation.md
  docs/src/particles.md
  docs/src/primitiveequation.md
  docs/src/setups.md
  docs/src/shallowwater.md
  src/dynamics/tendencies.jl
  src/physics/land_sea_mask.jl
Labels: documentation :books:

#484 ParticleTracker with netCDF
  docs/src/particles.md
  src/SpeedyWeather.jl
  src/dynamics/clock.jl
  src/dynamics/prognostic_variables.jl
  src/output/output.jl
  src/output/particle_tracker.jl
  test/particle_advection.jl
Labels: output :outbox_tray:, particles :balloon:

#485 rand(Particle) cos-distribution corrected
  src/dynamics/particle_advection.jl
  src/dynamics/particles.jl
Labels: bug :lady_beetle:, particles :balloon:

#486 Update README.md
  README.md
Labels: documentation :books:

#488 Scheduler for callbacks
  docs/src/callbacks.md
  docs/src/particles.md
  src/SpeedyWeather.jl
  src/dynamics/clock.jl
  src/dynamics/particle_advection.jl
  src/models/simulation.jl
  src/output/particle_tracker.jl
  src/output/schedule.jl
Labels: user interface :musical_keyboard:, callback :phone:

#489 Zenodo DOI added
  README.md
Labels: documentation :books:, package :package:

#490 Schedule bug with millisecond time steps
  src/output/schedule.jl
  test/runtests.jl
  test/schedule.jl
Labels: bug :lady_beetle:, callback :phone:

#491 Update README.md with particle advection video
  README.md
Labels: documentation :books:

#492 Field trees
  docs/make.jl
  docs/src/structure.md
  src/SpeedyWeather.jl
  src/models/tree.jl
Labels: documentation :books:, structure :house:

#494 Export `coriolis`, unscale diagnostics at finish, add! callbacks directly to model too
  docs/src/callbacks.md
  docs/src/speedytransforms.md
  src/dynamics/coriolis.jl
  src/dynamics/scaling.jl
  src/dynamics/time_integration.jl
  src/output/callbacks.jl
  test/callbacks.jl
Labels: user interface :musical_keyboard:

#495 Trees with summarysize
  docs/src/structure.md
  src/SpeedyWeather.jl
  src/models/tree.jl
Labels: user interface :musical_keyboard:, structure :house:

#496 ConstantOceanClimatology, AquaPlanet
  docs/make.jl
  docs/src/callbacks.md
  docs/src/land_sea_mask.md
  docs/src/ocean.md
  docs/src/parameterizations.md
  docs/src/radiation.md
  docs/src/setups.md
  docs/src/surface_fluxes.md
  src/physics/column_variables.jl
  src/physics/land_sea_mask.jl
  src/physics/ocean.jl
  test/ocean.jl
  test/runtests.jl
Labels: parameterizations :cloud_with_rain:, surface :mountain:, ocean :ocean:

#497 Document typical online analysis steps
  docs/make.jl
  docs/src/analysis.md
  docs/src/barotropic.md
  docs/src/land_sea_mask.md
Labels: documentation :books:

#498 Convection with work arrays for thread safety
  src/dynamics/diagnostic_variables.jl
  src/dynamics/scaling.jl
  src/dynamics/time_integration.jl
  src/physics/convection.jl
  src/physics/define_column.jl
  test/convection.jl
Labels: parallel :racehorse:, parameterizations :cloud_with_rain:, humidity :droplet:

#501 LowerTriangularMatrix copyto! range bug
  src/LowerTriangularMatrices/lower_triangular_matrix.jl
  test/lower_triangular_matrix.jl
Labels: bug :lady_beetle:, array types :globe_with_meridians:

#499 Bulk Richardson-based vertical diffusion
  src/dynamics/hole_filling.jl
  src/dynamics/vertical_advection.jl
  src/dynamics/vertical_coordinates.jl
  src/models/primitive_dry.jl
  src/models/primitive_wet.jl
  src/physics/boundary_layer.jl
  src/physics/column_variables.jl
  src/physics/define_column.jl
  src/physics/large_scale_condensation.jl
  src/physics/tendencies.jl
  src/physics/thermodynamics.jl
  src/physics/vertical_diffusion.jl
Labels: parameterizations :cloud_with_rain:, surface :mountain:

#502 Jeevanjee longwave radiation
  src/dynamics/diagnostic_variables.jl
  src/dynamics/orography.jl
  src/dynamics/planet.jl
  src/dynamics/time_integration.jl
  src/models/abstract_models.jl
  src/models/barotropic.jl
  src/models/primitive_dry.jl
  src/models/primitive_wet.jl
  src/models/shallow_water.jl
  src/models/tree.jl
  src/output/feedback.jl
  src/output/plot.jl
  src/output/schedule.jl
  src/physics/albedo.jl
  src/physics/column_variables.jl
  src/physics/define_column.jl
  src/physics/longwave_radiation.jl
  src/physics/shortwave_radiation.jl
  src/physics/tendencies.jl
  src/physics/zenith.jl
  test/radiation.jl
Labels: parameterizations :cloud_with_rain:, new defaults :new:, radiation :sun_with_face:

#505 Add to analysis doc (from new branch)
  docs/src/analysis.md
Labels: documentation :books:
