Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2024-07, with the labels that each got.

#543 Change LowerTriangularArrays to be subtype of AbstractArray{T,N-1}
  docs/src/lowertriangularmatrices.md
  docs/src/speedytransforms.md
  ext/SpeedyWeatherJLArraysExt.jl
  src/LowerTriangularMatrices/LowerTriangularMatrices.jl
  src/LowerTriangularMatrices/lower_triangular_matrix.jl
  src/LowerTriangularMatrices/plot.jl
  src/SpeedyTransforms/SpeedyTransforms.jl
  src/SpeedyTransforms/legendrepolarray.jl
  src/SpeedyTransforms/spectral_gradients.jl
  src/SpeedyTransforms/spectral_transform.jl
  src/SpeedyTransforms/spectral_truncation.jl
  src/SpeedyTransforms/spectrum.jl
  src/SpeedyWeather.jl
  src/dynamics/horizontal_diffusion.jl
  src/dynamics/implicit.jl
  src/dynamics/orography.jl
  src/dynamics/prognostic_variables.jl
  test/diffusion.jl
  test/extending.jl
  test/lower_triangular_matrix.jl
  test/runtests.jl
  test/spectral_gradients.jl
  test/spectral_transform.jl
  test/time_stepping.jl
Labels: performance :rocket:, transform :arrow_left: :arrow_right:, array types :globe_with_meridians:

#561 LTA: copyto! for Vectors
  docs/src/lowertriangularmatrices.md
  src/LowerTriangularMatrices/lower_triangular_matrix.jl
  test/lower_triangular_matrix.jl
Labels: array types :globe_with_meridians:

#562 LTA: colon indexing for LTM
  src/LowerTriangularMatrices/lower_triangular_matrix.jl
  test/lower_triangular_matrix.jl
Labels: array types :globe_with_meridians:

#559 Create CHANGELOG.md
  .github/workflows/enforce_changelog.yml
  CHANGELOG.md
Labels: compatibility :dancers:, package :package:
