Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2024-09, with the labels that each got.

#572 RingGrids: Fix RingGrids Array conversion
  .gitignore
  CHANGELOG.md
  docs/src/examples_2D.md
  docs/src/ringgrids.md
  docs/src/speedytransforms.md
  src/RingGrids/full_grids.jl
  src/RingGrids/general.jl
  src/dynamics/orography.jl
  src/output/output.jl
  src/physics/albedo.jl
  src/physics/land.jl
  src/physics/land_sea_mask.jl
  test/grids.jl
Labels: bug :lady_beetle:, array types :globe_with_meridians:

#563 Set! function for PrognosticVariables and ICs for new structure
  CHANGELOG.md
  docs/src/structure.md
  src/LowerTriangularMatrices/lower_triangular_matrix.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/prognostic_variables.jl
  test/lower_triangular_matrix.jl
  test/runtests.jl
  test/set.jl
  test/set_vars.jl
Labels: user interface :musical_keyboard:, array types :globe_with_meridians:, initial conditions :traffic_light:

#578 set! for orography
  CHANGELOG.md
  docs/src/analysis.md
  docs/src/examples_2D.md
  docs/src/gradients.md
  docs/src/how_to_run_speedy.md
  docs/src/index.md
  docs/src/land_sea_mask.md
  docs/src/orography.md
  src/dynamics/orography.jl
Labels: user interface :musical_keyboard:, surface :mountain:

#580 Set! documentation / keywords
  CHANGELOG.md
  src/dynamics/orography.jl
  src/dynamics/prognostic_variables.jl
Labels: documentation :books:, user interface :musical_keyboard:
