Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2024-01, with the labels that each got.

#426 Export forcing!, drag!, etc for extending those with fewer conflicts
  src/SpeedyWeather.jl
  test/extending.jl
Labels: user interface

#429 Add compat entry for NCDatasets v0.14
  Project.toml
Labels: compatibility, package

#428 Use Julia v1.10 for CI and building Docs
  .github/workflows/CI.yml
  .github/workflows/DocPreviewCleanup.yml
  .github/workflows/Documenter.yml
  Project.toml
Labels: testing, package

#430 Adjust time step with radius
  src/dynamics/spectral_grid.jl
  src/dynamics/time_integration.jl
Labels: time integration

#427 CompatHelper: bump compat for Adapt to 4, (keep existing compat)
  Project.toml
Labels: compatibility

#431 Add remark about Julia compat
  docs/src/installation.md
Labels: documentation

#432 Switch off dynamics
  src/SpeedyWeather.jl
  src/dynamics/models.jl
  src/dynamics/orography.jl
  src/dynamics/tendencies.jl
  src/dynamics/tendencies_dynamics.jl
  src/dynamics/time_integration.jl
Labels: testing, parameterizations

#433 Vertical diffusion of humidity
  src/SpeedyWeather.jl
  src/abstract_types.jl
  src/dynamics/hole_filling.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/models.jl
  src/dynamics/tendencies.jl
  src/dynamics/time_integration.jl
  src/output/feedback.jl
  src/physics/boundary_layer.jl
  src/physics/column_variables.jl
  src/physics/define_column.jl
  src/physics/large_scale_condensation.jl
  src/physics/surface_fluxes.jl
  src/physics/tendencies.jl
  src/physics/thermodynamics.jl
  src/physics/vertical_diffusion.jl
  test/netcdf_output.jl
  test/spectral_gradients.jl
Labels: parameterizations, vertical, humidity

#435 NoBoundaryLayer but TemperatureRelaxation default for dry & wet models
  src/dynamics/models.jl
  src/physics/tendencies.jl
Labels: forcing, new defaults

#438 Solar zenith angle calculation
  src/RingGrids/grids_general.jl
  src/SpeedyWeather.jl
  src/abstract_types.jl
  src/dynamics/models.jl
  src/dynamics/planets.jl
  src/dynamics/spectral_grid.jl
  src/physics/tendencies.jl
  src/physics/zenith.jl
  src/utility_functions.jl
Labels: parameterizations, forcing
