Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2024-02, with the labels that each got.

#439 ImmediateCondensation and Clausius-Clapeyron
  src/abstract_types.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/models.jl
  src/dynamics/vertical_advection.jl
  src/physics/column_variables.jl
  src/physics/define_column.jl
  src/physics/large_scale_condensation.jl
  src/physics/surface_fluxes.jl
  src/physics/tendencies.jl
  src/physics/thermodynamics.jl
  src/physics/vertical_diffusion.jl
  src/physics/zenith.jl
Labels: parameterizations, new defaults, humidity

#440 Flux limiters for surface drag and heat fluxes
  src/dynamics/models.jl
  src/dynamics/vertical_coordinates.jl
  src/physics/surface_fluxes.jl
  src/physics/tendencies.jl
Labels: parameterizations, vertical

#442 Simplified BettsMiller convection
  src/dynamics/models.jl
  src/physics/column_variables.jl
  src/physics/convection.jl
  src/physics/large_scale_condensation.jl
  src/physics/thermodynamics.jl
  src/physics/zenith.jl
  src/utility_functions.jl
Labels: parameterizations, new defaults, vertical, humidity

#444 Simple radiation schemes: UniformCooling, TransparentShortwave
  src/SpeedyWeather.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/models.jl
  src/physics/column_variables.jl
  src/physics/convection.jl
  src/physics/define_column.jl
  src/physics/large_scale_condensation.jl
  src/physics/longwave_radiation.jl
  src/physics/shortwave_radiation.jl
  src/physics/surface_fluxes.jl
  src/physics/tendencies.jl
  src/physics/thermodynamics.jl
  test/column_variables.jl
  test/convection.jl
  test/large_scale_condensation.jl
  test/longwave_radiation.jl
  test/shortwave_radiation.jl
  test/thermodynamics.jl
Labels: parameterizations, vertical, radiation

#447 ImplicitCondensation not immediate anymore
  src/SpeedyWeather.jl
  src/abstract_types.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/models.jl
  src/dynamics/time_integration.jl
  src/physics/column_variables.jl
  src/physics/large_scale_condensation.jl
  src/physics/ocean.jl
Labels: parameterizations, humidity, time integration

#453 Run LowerTriangularMatrix and output examples while building the docs
  docs/src/lowertriangularmatrices.md
  docs/src/output.md
Labels: documentation

#451 Use `Documenter.@docs` functionality to display docstring in Documentation
  .github/workflows/Documenter.yml
  docs/Project.toml
  docs/make.jl
  docs/src/output.md
Labels: documentation

#454 Some more examples running live in the Docs
  docs/src/extending.md
  src/output/feedback.jl
Labels: documentation

#458 Collapse levels to streamline the documentation navigation
  docs/make.jl
Labels: documentation
