Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2025-09, with the labels that each got.

#835 Compat entries for Subpackages
  CHANGELOG.md
  LowerTriangularArrays/Project.toml
  RingGrids/Project.toml
  SpeedyInternals/Project.toml
  SpeedyTransforms/Project.toml
  SpeedyTransforms/README.md
Labels: compatibility :dancers:, package :package:, dependencies

#830 Start with soil moisture, temperature, SST, sea ice from climatology
  CHANGELOG.md
  src/output/feedback.jl
  src/physics/land/soil_moisture.jl
  src/physics/land/temperature.jl
  src/physics/ocean.jl
Labels: land :earth_africa:

#841 Add compat entries of submodules to main env
  CHANGELOG.md
  Project.toml
Labels: compatibility :dancers:, package :package:

#842 Add logo to docs
  CHANGELOG.md
  README.md
  docs/src/assets/logo-dark.png
  docs/src/assets/logo.png
Labels: documentation :books:

#852 Call callbacks before output
  CHANGELOG.md
  src/dynamics/time_integration.jl
Labels: output :outbox_tray:, callback :phone:

#850 Fix correct array type for LTA init
  CHANGELOG.md
  LowerTriangularArrays/src/lower_triangular_array.jl
  SpeedyTransforms/src/spectral_transform.jl
Labels: gpu :framed_picture:, array types :1234:

#853 Mean sea-level pressure output
  CHANGELOG.md
  docs/src/output.md
  ext/SpeedyWeatherGeoMakieExt.jl
  src/output/netcdf_output.jl
  src/output/variables/dynamics.jl
  src/output/variables/output_variables.jl
  test/output/netcdf_output.jl
Labels: output :outbox_tray:, dynamics :wavy_dash:

#866 Move Makie extensions to RingGrids and fix `globe` bug
  CHANGELOG.md
  Project.toml
  RingGrids/Project.toml
  RingGrids/ext/RingGridsGeoMakieExt.jl
  RingGrids/ext/RingGridsMakieExt.jl
  RingGrids/src/RingGrids.jl
  ext/SpeedyWeatherGeoMakieExt.jl
  src/SpeedyWeather.jl
  test/Project.toml
  test/grids/grids.jl
  test/grids/makie.jl
Labels: bug :lady_beetle:, structure :house:, visualisation :framed_picture:
