Repository SpeedyWeather/SpeedyWeather.jl, pull requests merged in 2025-05, with the labels that each got.

#724 Remove jld2 & nc files from docs after make before deploy
  CHANGELOG.md
  docs/make.jl
Labels: documentation :books:

#720 Reverse for LowerTriangularArray
  CHANGELOG.md
  docs/src/lowertriangularmatrices.md
  src/LowerTriangularMatrices/LowerTriangularMatrices.jl
  src/LowerTriangularMatrices/rotate.jl
  src/LowerTriangularMatrices/rotate_reverse.jl
  test/transforms/lower_triangular_matrix.jl
Labels: array types :1234:, spectral :wavy_dash:

#725 Update docs urls
  CHANGELOG.md
  README.md
Labels: documentation :books:

#729 Baroclinic wave divergence free
  CHANGELOG.md
  docs/src/examples_3D.md
  src/dynamics/initial_conditions.jl
Labels: bug :lady_beetle:, dynamics :wavy_dash:, initial conditions :traffic_light:

#728 Move UnicodePlots to extension
  CHANGELOG.md
  Project.toml
  README.md
  docs/src/examples_2D.md
  docs/src/examples_3D.md
  docs/src/how_to_run_speedy.md
  docs/src/orography.md
  docs/src/ringgrids.md
  docs/src/speedytransforms.md
  ext/SpeedyWeatherUnicodePlotsExt.jl
  src/LowerTriangularMatrices/LowerTriangularMatrices.jl
  src/LowerTriangularMatrices/plot.jl
  src/RingGrids/RingGrids.jl
  src/RingGrids/show.jl
  src/SpeedyWeather.jl
  src/models/simulation.jl
  src/output/plot.jl
Labels: dependency :guide_dog:, visualisation :framed_picture:

#731 Reduce CI time
  CHANGELOG.md
  test/dynamics/vertical_advection.jl
  test/grids/grids.jl
  test/physics/albedo.jl
  test/physics/land.jl
  test/transforms/lower_triangular_matrix.jl
Labels: performance :rocket:, testing :test_tube:

#734 Introduce Spectrum for LowerTriangularArrays
  CHANGELOG.md
  README.md
  benchmark/README.md
  docs/joss/paper.md
  docs/make.jl
  docs/src/gradients.md
  docs/src/lowertriangularmatrices.md
  docs/src/spectral_transform.md
  docs/src/speedytransforms.md
  ext/SpeedyWeatherCUDAExt/SpeedyWeatherCUDAExt.jl
  ext/SpeedyWeatherCUDAExt/legendre.jl
  ext/SpeedyWeatherJLArraysExt.jl
  src/LowerTriangularArrays/LowerTriangularArrays.jl
  src/LowerTriangularArrays/lower_triangular_array.jl
  src/LowerTriangularArrays/rotate_reverse.jl
  src/LowerTriangularArrays/spectrum.jl
  src/SpeedyTransforms/SpeedyTransforms.jl
  src/SpeedyTransforms/aliasing.jl
  src/SpeedyTransforms/legendre.jl
  src/SpeedyTransforms/legendrepolarray.jl
  src/SpeedyTransforms/show.jl
  src/SpeedyTransforms/spectral_transform.jl
  src/SpeedyTransforms/spectral_truncation.jl
  src/SpeedyWeather.jl
  src/dynamics/diagnostic_variables.jl
  src/dynamics/drag.jl
  src/dynamics/implicit.jl
  src/dynamics/initial_conditions.jl
  src/dynamics/prognostic_variables.jl
  src/dynamics/spectral_grid.jl
  test/GPU/spectral_transform.jl
  test/differentiability/speedy_transforms.jl
  test/dynamics/diffusion.jl
  test/dynamics/set.jl
  test/transforms/lower_triangular_matrix.jl
  test/transforms/spectral_gradients.jl
  test/transforms/spectral_transform.jl
  test/transforms/spectral_transform_ad_rules.jl
  test/transforms/spectrum.jl
Labels: array types :1234:, spectral :wavy_dash:
